# Site settings
baseurl = "/"
languageCode = "en-US"
title = "Mark Arneman"
theme = "arneman"
# googleAnalytics = "your_google_analytics_id"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = false

[params]
author = "Mark Arneman"
description = "Mark Arneman's personal webpage"
bio = "[mark@arneman.me](mailto:mark@arneman.me)"

twitter = "bearlikelion"
facebook = "bearlikelion"

enableRSS = true
enableToc = true

enableDisqus = true
disqusShortname = "arneman-me"

enableSummary = true
summaryLength = 10
# Set the value to true if use description in post front matter replace content summary
useDescriptionReplaceSummary = false

enableGoogleAnalytics = true

enableTwitterCard = false
# The url for twitter card image, default is avatar.png in static/images directory
twitterCardImage = ""

# Add custom assets with their paths relative to the static folder
customCSS = []
customJS  = []

# The variables below are optionally too and can be used to
# translate or customize each string of the theme.

# Navigation links
home = ""
about = "About Me"
archive = ""
projects = ""
subscribe = "RSS"

olderPosts = ""
newerPosts = ""
copyright = ""

# show latest posts in single page
showLatestPosts = true
readMore = ""

# Share
enableShare = false
tweet = ""
share = ""

# 404 page
title404 = ""
subtitle404 = ""

# Add additional social link entries underneath
[social]
	facebook-square = "https://facebook.com/bearlikelion"
	github-square = "https://github.com/bearlikelion"
	linkedin = "https://linkedin.com/in/markarneman"
	twitter-square = "https://twitter.com/bearlikelion"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
