# Site settings
baseurl = "/"
languageCode = "en-US"
title = "Mark Arneman"
theme = "arneman"

# Disable page types not used in single-page layout
disableKinds = ["taxonomy", "term"]

[params]
author = "Mark Arneman"
description = "Mark Arneman's online portfolio."

enableGoogleAnalytics = true
googleAnalytics = "UA-48666725-1"

# Ignore legacy content directories
ignoreFiles = ["content/posts/.*", "content/projects/.*"]

