name = "Arneman"
license = "MIT"
licenselink = ""
description = "A minimalistic gruvbox dark theme"
homepage = "https://arneman.me"
tags = ["gruvbox", "dark", "minimalistic", "minimal"]
features = ["gruvbox", "dark", "minimalistic", "minimal"]
min_version = 0.20

[author]
  name = "Mark Arneman"
  homepage = "https://arneman.me"
